version: '3.8'

services:
  backend:
    build:
      context: notebooks/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - BASE_URL=http://127.0.0.1:8000
    expose:
      - 8000

  frontend:
    env_file:
      - frontend/.env
    build:
      context: frontend/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3000:3000"
    expose:
      - 3000
