# Utiliser une image Python officielle
FROM python:3.11-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers nécessaires dans le conteneur
COPY . /app

# Installer les dépendances
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Installer MLFlow
RUN pip install mlflow

# Exposer le port MLFlow et celui de votre application Flask
EXPOSE 5000
EXPOSE 1234

# Commande pour exécuter MLFlow et Flask
CMD ["sh", "-c", "mlflow ui --host 0.0.0.0 --port 1234 & python app.py"]

