name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - staging
      - main
permissions:
  contents: write

jobs:
  # build and test on pull request to dev
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        pip install dvc[gs] mlflow

    - name: Run integration tests
      run: pytest tests/test_integration/

    - name: Push to staging branch
      if: github.ref == 'refs/heads/dev' && success()
      run: |
        git checkout -b staging
        git push origin staging

  staging:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      working-directory: notebooks
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Start API Server
      working-directory: notebooks
      run: |
        source venv/bin/activate
        python app.py &
      env:
        BASE_URL: http://127.0.0.1:5000

    # Install Node.js for Cypress tests
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Install Cypress dependencies
    - name: Install frontend dependencies
      working-directory: frontend
      run: npm install

    - name: Start Frontend Server
      working-directory: frontend
      run: |
        npm start &
        npx wait-on http://localhost:3000

    - name: Run integration tests
      run: pytest tests/test_integration/

    - name: Run unit tests
      run: pytest tests/test_unit/
      
    # run cypress tests
    - name: Run e2e tests (cypress)
      working-directory: frontend
      run: npx cypress run

    - name: Push to production branch
      if: github.ref == 'refs/heads/staging' && success()
      run: |
        git checkout -b main
        git push origin main

  production:
    needs: staging
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    # Push Docker image to DockerHub
    - name: Build and push backend
      working-directory: notebooks
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/sentiment-analyzer_backend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/sentiment-analyzer_backend:latest
       
    - name: Build and push frontend
      working-directory: frontend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/sentiment-analyzer_frontend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/sentiment-analyzer_frontend:latest 


    - name: Deploy to production
      run: |
        echo "Deployment to production server or cloud service. e.g., AWS, Kubernetes, etc."
